#!/bin/sh
set -e

# create user if it doesn't exist
create_user() {
	USER_NAME=${USER_NAME:-"user"}
	addgroup -g ${USER_GID} ${USER_NAME} 2> /dev/null || true
	adduser -S -u ${USER_UID} -G ${USER_NAME} -s /bin/ash ${USER_NAME} 2> /dev/null || true
	echo "${USER_NAME} ALL=NOPASSWD: ALL" > "/etc/sudoers.d/${USER_NAME}"
}

main() {
	# load addons environment variables
	for ADDON_NAME in $PHP_ADDONS_LIST; do
		ADDON_SCRIPT="/php-addons/$ADDON_NAME.sh"
		if [ -f "$ADDON_SCRIPT" ];then
			source $ADDON_SCRIPT setenv
		fi
	done

	# append the PHP command if the first argument if a non executable PHP file
	if [[ -f "$1" && "${1##*.}" = "php" ]]; then
		set -- php "$@"
	fi

	# append the PHP command if the first argument contains a dash (php options) 
	if [ "${1#-}" != "$1" ]; then
		set -- php "$@"
	fi

	# execute the commamd with a given user
	if [ -n "${USER_UID+x}" ] && [ -n "${USER_GID+x}" ];then
		create_user
		set -- su-exec ${USER_UID}:${USER_GID} "$@"
	fi

	"$@"
}

main "$@"