#!/bin/sh
set -e

# create user if it doesn't exist
create_user() {
	USER_NAME=${USER_NAME:-"user"}
	addgroup -g ${USER_GID} ${USER_NAME} 2> /dev/null || true
	adduser -S -u ${USER_UID} -G ${USER_NAME} -s /bin/ash ${USER_NAME} 2> /dev/null || true
}

main() {
	# load addons environment variables
	for ADDON_NAME in $PHP_ADDONS_LIST; do
		ADDON_SCRIPT="/php-addons/$ADDON_NAME.sh"
		if [ -f "$ADDON_SCRIPT" ];then
			source $ADDON_SCRIPT setenv
		fi
	done

	# append the php command if the first argument if a file
	if [ -f "$1" ]; then
		set -- php "$@"
	fi

	# append the php command if the first argument contains a dash
	if [ "${1#-}" != "$1" ]; then
		set -- php "$@"
	fi

	# execute the php script with a given user
	if [ ! -z "${USER_UID}" ] && [ ! -z "${USER_GID}" ];then
		create_user
		set -- su-exec ${USER_UID}:${USER_GID} "$@"
	fi

	exec "$@"
}

main "$@"